[Icon Theme]
Name=AD-integration Kora
Name[ru]=AD-интеграция Кора
Comment=Icon theme for AD integration BaseAlt projects

Inherits=breeze,Adwaita,hicolor,Kora

Example=Container

FollowsColorScheme=true

# KDE Specific Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

# Directory list
Directories=scalable

[scalable]
Context=Categories
Size=16
MinSize=8
MaxSize=512
Type=Scalable
